/**
 * @file    buttons.h
 * @brief   Button handling module interface.
 *
 * @details
 * This module provides an abstraction layer for handling
 * physical buttons.
 *
 * Features:
 *  - button initialization
 *  - event-based button state reading
 *
 * Design notes:
 *  - button events are generated by interrupts (EXTI)
 *  - debouncing is handled internally
 *  - events are latched and cleared after reading
 *
 * Architecture:
 *  - input / hardware abstraction layer
 *  - no application logic
 */

#ifndef BUTTONS_H
#define BUTTONS_H

#include <stdint.h>
#include <stdbool.h>
#include "FreeRTOS.h"
#include "queue.h"

/**
 * @brief Button identifiers.
 */
typedef enum
{
    BUTTON_GRAPH_MODE = 0,
	BUTTON_SET_BASE_PRESSURE,
	BUTTON_COUNT
} ButtonId;

typedef struct {
    ButtonId id;
} ButtonEvent_t;

QueueHandle_t Buttons_GetQueue(void);

void Buttons_Queue_Init(void);

/**
 * @brief Initialize button subsystem.
 *
 * Configures GPIO and EXTI for button inputs.
 * Must be called once during system initialization.
 */
void Buttons_GPIO_Init(void);

#endif /* BUTTONS_H */
