/**
 * @file    buttons.h
 * @brief   Button handling module interface.
 *
 * @details
 * This module provides an abstraction layer for handling
 * physical buttons.
 *
 * Features:
 *  - button initialization
 *  - event-based button state reading
 *
 * Design notes:
 *  - button events are generated by interrupts (EXTI)
 *  - debouncing is handled internally
 *  - events are latched and cleared after reading
 *
 * Architecture:
 *  - input / hardware abstraction layer
 *  - no application logic
 */

#ifndef BUTTONS_H
#define BUTTONS_H

#include <stdint.h>
#include <stdbool.h>

/**
 * @brief Button identifiers.
 */
typedef enum
{
    BUTTON_GRAPH_MODE = 0,
	BUTTON_SET_BASE_PRESSURE,
	BUTTON_COUNT
} ButtonId;

/**
 * @brief Initialize button subsystem.
 *
 * Configures GPIO and EXTI for button inputs.
 * Must be called once during system initialization.
 */
void Buttons_Init(void);

/**
 * @brief Check and clear button event.
 *
 * Returns true if a button press event occurred
 * since the last call for the specified button.
 *
 * @param id Button identifier
 *
 * @retval true   Button event detected
 * @retval false  No button event
 */
bool Buttons_GetEvent(ButtonId id);

#endif /* BUTTONS_H */
